# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # Explicit connection bindings for migration services
    App\Migration\Limpiador:
        arguments:
            $newConn: "@doctrine.dbal.default_connection"

    PDO $oldPdo:
        class: \PDO
        arguments:
            $dsn: "dblib:host=%env(systemfdn_host)%:%env(systemfdn_port)%;dbname=%env(systemfdn_dbname)%"
            $username: "%env(systemfdn_user)%"
            $password: "%env(systemfdn_password)%"

    App\Security\Voter\ActionVoter:
        tags: ['security.voter']
        arguments:
            $permissionManager: '@App\Security\PermissionManager'

    App\Security\Voter\EntityVoter:
        tags: ['security.voter']
        arguments:
            $permissionManager: '@App\Security\PermissionManager'

    App\Security\ActionExpressionProvider:
        tags:
            - { name: 'security.expression_language_provider' }

    App\Services\UsuarioPasswordHasher:
        bind:
            $processor: "@api_platform.doctrine.orm.state.persist_processor"

    App\Replication\ReplicationService:
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }

