# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        scoped_clients:
            eforcon.client:
                headers: { "Content-Type": "application/json" }
                base_uri: "%env(eforcon_basic_url)%"
                # auth_basic: "%env(eforcon_user)%:%env(eforcon_password)%"

            cybersource.client:
                base_uri: "%env(CYBERSOURCE_BASE_URI)%"

            fdn.client:
                headers: { "Content-Type": "application/json" }
                base_uri: "%fdn_base_uri%"
