erDiagram
    %% ===== CONFIGURACION =====
    CollectionFieldConfig {
    }
    FormFieldConfig {
    }
    EntityConfiguration {
        string string PK NOT NULL
    }
    %% ===== FLOTA =====
    Bus {
        string string NOT NULL
        string int NOT NULL
    }
    Piloto {
        string string NOT NULL
    }
    Asiento {
    }
    BusMarca {
        string string NOT NULL
    }
    Enclave {
    }
    %% ===== INFRAESTRUCTURA =====
    IconCategory {
    }
    Icon {
    }
    %% ===== ORGANIZACION =====
    Localidad {
    }
    Nacion {
    }
    Parada {
    }
    Empresa {
    }
    Estacion {
    }
    %% ===== OTROS =====
    Permiso {
    }
    %% ===== PERSONAL =====
    Usuario {
        string string NOT NULL
    }
    %% ===== SEGURIDAD =====
    Action {
    }
    Role {
    }
    ApiToken {
        string string NOT NULL
    }
    %% ===== TRANSPORTE =====
    Boleto {
    }
    Servicio {
    }
    Factura {
    }
    Status {
    }
    Recorrido {
    }
    Trayecto {
    }
    Cliente {
    }
    RecorridoMatrioska {
    }
    Venta {
    }
    %% ===== RELATIONSHIPS =====
    Usuario ||--o{ Collection : "Collection"
    Usuario ||--o{ Collection : "Collection"
    Usuario }{o--o{ Collection : "Collection"
    Usuario }{o--o{ Collection : "Collection"
    Servicio ||--o{ Collection : "Collection"
    Bus ||--o{ Collection : "Collection"
    Action }{o--o{ Collection : "Collection"
    Action }{o--o{ Collection : "Collection"
    Recorrido ||--o{ Collection : "Collection"
    Trayecto ||--o{ Collection : "Collection"
    Trayecto }{o--o{ Collection : "Collection"
    Empresa ||--o{ Collection : "Collection"
    Empresa ||--o{ Collection : "Collection"
    Venta ||--o{ Collection : "Collection"
    Enclave ||--o{ Collection : "Collection"
    CollectionFieldConfig }|--|| EntityConfiguration : "EntityConfiguration"
    FormFieldConfig }|--|| EntityConfiguration : "EntityConfiguration"