<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Anulación y reasignación de boletos y bitácora de salidas y boletos
 * (ADR-028):
 *
 * - `bitacora`: traza de solo agregar, sin clave foránea al registro (sobrevive
 *   a que se elimine).
 * - `factura.anulada_en` / `motivo_anulacion`: el DTE anulado en el certificador.
 * - `boleto_asiento.reasignado_de_id` y la unicidad (asiento, trayecto, salida)
 *   solo entre boletos vivos: un asiento anulado o reasignado se puede revender.
 * - Acciones `boleto.anular` / `boleto.reasignar` y su permiso.
 */
final class Version20261010100000 extends AbstractMigration
{
    private const PERMISO = 'Anulacion y Reasignacion de Boletos';

    private const ACCIONES = [
        'boleto.anular' => 'Anular boletos',
        'boleto.reasignar' => 'Reasignar boletos',
    ];

    public function getDescription(): string
    {
        return 'Bitácora (salida, boleto), factura anulada, boleto reasignado y acciones boleto.anular / boleto.reasignar';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bitacora (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entidad VARCHAR(20) NOT NULL, registro_id INT NOT NULL, operacion VARCHAR(30) NOT NULL, usuario_nombre VARCHAR(100) DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, detalle JSON DEFAULT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9087FEF9DB38439E ON bitacora (usuario_id)');
        $this->addSql('CREATE INDEX idx_bitacora_registro ON bitacora (entidad, registro_id, fecha)');
        $this->addSql('ALTER TABLE bitacora ADD CONSTRAINT FK_9087FEF9DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('ALTER TABLE factura ADD anulada_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE factura ADD motivo_anulacion VARCHAR(255) DEFAULT NULL');

        $this->addSql('DROP INDEX uq_boleto_asiento_asiento_trayecto_salida');
        $this->addSql('ALTER TABLE boleto_asiento ADD reasignado_de_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT FK_8594A004B6C7CEA5 FOREIGN KEY (reasignado_de_id) REFERENCES boleto_asiento (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8594A004B6C7CEA5 ON boleto_asiento (reasignado_de_id)');
        $this->addSql("CREATE UNIQUE INDEX uq_boleto_asiento_asiento_trayecto_salida ON boleto_asiento (asiento_id, trayecto_id, salida_id) WHERE estado NOT IN ('anulado', 'reasignado')");

        $this->addSql(
            'INSERT INTO permiso (nombre) SELECT :nombre WHERE NOT EXISTS (SELECT 1 FROM permiso WHERE nombre = :nombre)',
            ['nombre' => self::PERMISO],
        );
        foreach (self::ACCIONES as $codigo => $nombre) {
            $this->addSql(
                'INSERT INTO action (codigo, nombre) SELECT :codigo, :nombre WHERE NOT EXISTS (SELECT 1 FROM action WHERE codigo = :codigo)',
                ['codigo' => $codigo, 'nombre' => $nombre],
            );
            $this->addSql(
                'INSERT INTO permiso_action (permiso_id, action_id)
                 SELECT p.id, a.id FROM permiso p, action a WHERE p.nombre = :nombre AND a.codigo = :codigo
                 ON CONFLICT DO NOTHING',
                ['nombre' => self::PERMISO, 'codigo' => $codigo],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DELETE FROM permiso WHERE nombre = :nombre', ['nombre' => self::PERMISO]);
        $this->addSql('DROP INDEX uq_boleto_asiento_asiento_trayecto_salida');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT FK_8594A004B6C7CEA5');
        $this->addSql('DROP INDEX IDX_8594A004B6C7CEA5');
        $this->addSql('ALTER TABLE boleto_asiento DROP reasignado_de_id');
        $this->addSql('CREATE UNIQUE INDEX uq_boleto_asiento_asiento_trayecto_salida ON boleto_asiento (asiento_id, trayecto_id, salida_id)');
        $this->addSql('ALTER TABLE factura DROP anulada_en');
        $this->addSql('ALTER TABLE factura DROP motivo_anulacion');
        $this->addSql('DROP TABLE bitacora');
    }
}
