<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tarifas como en el legado (ADR-021, enmienda 2026-10): clase de bus
 * (`bus_clase`, `bus.clase_id`, `boleto_tarifa.bus_clase_id`), horario
 * (`hora` exacta → `hora_desde`/`hora_hasta`; una hora exacta queda como
 * horario de un solo minuto) y vigencia (`vigente_desde`; las existentes
 * rigen desde ya). Para corregir las tarifas ya migradas hay que volver a
 * migrar la entidad "tarifa" (y "bus_clase" y "bus") desde /migracion.
 */
final class Version20261002180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tarifas: bus_clase, bus.clase_id, horario y vigencia en boleto_tarifa';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS bus_clase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(50) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');

        $this->addSql('ALTER TABLE bus ADD COLUMN IF NOT EXISTS clase_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_2F566B699F720353 ON bus (clase_id)');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT IF EXISTS FK_2F566B699F720353');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B699F720353 FOREIGN KEY (clase_id) REFERENCES bus_clase (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE boleto_tarifa RENAME COLUMN hora TO hora_desde');
        $this->addSql('ALTER TABLE boleto_tarifa ADD hora_hasta TIME(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('UPDATE boleto_tarifa SET hora_hasta = hora_desde');
        $this->addSql('ALTER TABLE boleto_tarifa ADD vigente_desde TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE boleto_tarifa ALTER vigente_desde DROP DEFAULT');
        $this->addSql('ALTER TABLE boleto_tarifa ADD bus_clase_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_9CC7BCC87A0CA64F ON boleto_tarifa (bus_clase_id)');
        $this->addSql('ALTER TABLE boleto_tarifa ADD CONSTRAINT FK_9CC7BCC87A0CA64F FOREIGN KEY (bus_clase_id) REFERENCES bus_clase (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE boleto_tarifa DROP CONSTRAINT IF EXISTS FK_9CC7BCC87A0CA64F');
        $this->addSql('DROP INDEX IF EXISTS IDX_9CC7BCC87A0CA64F');
        $this->addSql('ALTER TABLE boleto_tarifa DROP bus_clase_id');
        $this->addSql('ALTER TABLE boleto_tarifa DROP vigente_desde');
        $this->addSql('ALTER TABLE boleto_tarifa DROP hora_hasta');
        $this->addSql('ALTER TABLE boleto_tarifa RENAME COLUMN hora_desde TO hora');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT IF EXISTS FK_2F566B699F720353');
        $this->addSql('DROP INDEX IF EXISTS IDX_2F566B699F720353');
        $this->addSql('ALTER TABLE bus DROP clase_id');
        $this->addSql('DROP TABLE IF EXISTS bus_clase');
    }
}
