<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Los buses se asocian a su molde con `bin/console app:croquis:asociar`
 * (la firma se calcula en PHP: `App\Croquis\Croquis::firma`).
 */
final class Version20261009120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Croquis como molde (ADR-027): croquis, bus.croquis_id y salida_bus_inferido (control de la migración)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE croquis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firma VARCHAR(40) NOT NULL, asientos SMALLINT NOT NULL, asientos_b SMALLINT NOT NULL, plantas SMALLINT NOT NULL, elementos JSON NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8630587A2BED3563 ON croquis (firma)');
        $this->addSql('ALTER TABLE bus ADD croquis_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B696B9CCFC0 FOREIGN KEY (croquis_id) REFERENCES croquis (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_2F566B696B9CCFC0 ON bus (croquis_id)');
        $this->addSql('CREATE TABLE salida_bus_inferido (criterio VARCHAR(10) NOT NULL, referencia_legado VARCHAR(30) DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, salida_id INT NOT NULL, bus_id INT NOT NULL, PRIMARY KEY (salida_id))');
        $this->addSql('CREATE INDEX IDX_C6D3EE462546731D ON salida_bus_inferido (bus_id)');
        $this->addSql('ALTER TABLE salida_bus_inferido ADD CONSTRAINT FK_C6D3EE4626A36E51 FOREIGN KEY (salida_id) REFERENCES salida (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida_bus_inferido ADD CONSTRAINT FK_C6D3EE462546731D FOREIGN KEY (bus_id) REFERENCES bus (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE salida_bus_inferido');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B696B9CCFC0');
        $this->addSql('DROP INDEX IDX_2F566B696B9CCFC0');
        $this->addSql('ALTER TABLE bus DROP croquis_id');
        $this->addSql('DROP TABLE croquis');
    }
}
