<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709070901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE icon_category_icon DROP CONSTRAINT fk_d0aece2454b9d732');
        $this->addSql('ALTER TABLE icon_category_icon DROP CONSTRAINT fk_d0aece2442b0e3d4');
        $this->addSql('DROP TABLE icon_category');
        $this->addSql('DROP TABLE icon_category_icon');
        $this->addSql('ALTER TABLE icon DROP codepoint');
        $this->addSql('ALTER TABLE icon DROP popularity');
        $this->addSql('ALTER TABLE icon DROP tags');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE icon_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE icon_category_icon (icon_category_id INT NOT NULL, icon_id INT NOT NULL, PRIMARY KEY (icon_category_id, icon_id))');
        $this->addSql('CREATE INDEX idx_d0aece2442b0e3d4 ON icon_category_icon (icon_category_id)');
        $this->addSql('CREATE INDEX idx_d0aece2454b9d732 ON icon_category_icon (icon_id)');
        $this->addSql('ALTER TABLE icon_category_icon ADD CONSTRAINT fk_d0aece2454b9d732 FOREIGN KEY (icon_id) REFERENCES icon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE icon_category_icon ADD CONSTRAINT fk_d0aece2442b0e3d4 FOREIGN KEY (icon_category_id) REFERENCES icon_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE icon ADD codepoint INT DEFAULT NULL');
        $this->addSql('ALTER TABLE icon ADD popularity INT DEFAULT NULL');
        $this->addSql('ALTER TABLE icon ADD tags JSON DEFAULT NULL');
    }
}
