<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930023817 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Factura electrónica con Forcon (ADR-021): establecimientos FEL, credenciales por empresa, afiliación IVA, frases, número de acceso de contingencia y PDF del DTE';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE credencial_fel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuario VARCHAR(100) NOT NULL, clave_cifrada TEXT NOT NULL, empresa_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54A68370521E1991 ON credencial_fel (empresa_id)');
        $this->addSql('CREATE TABLE establecimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo SMALLINT NOT NULL, nombre VARCHAR(255) DEFAULT NULL, empresa_id INT NOT NULL, estacion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_94A4D17E521E1991 ON establecimiento (empresa_id)');
        $this->addSql('CREATE INDEX IDX_94A4D17E2A4AF395 ON establecimiento (estacion_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_establecimiento_empresa_estacion ON establecimiento (empresa_id, estacion_id)');
        $this->addSql('ALTER TABLE credencial_fel ADD CONSTRAINT FK_54A68370521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE establecimiento ADD CONSTRAINT FK_94A4D17E521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE establecimiento ADD CONSTRAINT FK_94A4D17E2A4AF395 FOREIGN KEY (estacion_id) REFERENCES enclave (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto_venta ADD numero_acceso INT DEFAULT NULL');
        $this->addSql('ALTER TABLE empresa ADD afiliacion_iva VARCHAR(5) DEFAULT \'GEN\' NOT NULL');
        $this->addSql('ALTER TABLE empresa ADD frases_fel VARCHAR(100) DEFAULT \'1-1\' NOT NULL');
        $this->addSql('ALTER TABLE factura ADD url_pdf VARCHAR(500) DEFAULT NULL');
        // Establecimiento SAT 1 por defecto para las empresas existentes (revisar en Configuración).
        $this->addSql("INSERT INTO establecimiento (empresa_id, estacion_id, codigo, nombre) SELECT id, NULL, 1, 'Principal' FROM empresa");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE credencial_fel DROP CONSTRAINT FK_54A68370521E1991');
        $this->addSql('ALTER TABLE establecimiento DROP CONSTRAINT FK_94A4D17E521E1991');
        $this->addSql('ALTER TABLE establecimiento DROP CONSTRAINT FK_94A4D17E2A4AF395');
        $this->addSql('DROP TABLE credencial_fel');
        $this->addSql('DROP TABLE establecimiento');
        $this->addSql('ALTER TABLE boleto_venta DROP numero_acceso');
        $this->addSql('ALTER TABLE empresa DROP afiliacion_iva');
        $this->addSql('ALTER TABLE empresa DROP frases_fel');
        $this->addSql('ALTER TABLE factura DROP url_pdf');
    }
}
