<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Gestión de salidas (ADR-024): esquemas de salidas guardados desde el
 * programador y las acciones `salida.*` (ver, crear, editar, cancelar =
 * anular, eliminar) con su permiso "Gestion Salidas". Idempotente.
 */
final class Version20261002120000 extends AbstractMigration
{
    private const ACCIONES = [
        'salida.ver' => 'Ver salidas',
        'salida.crear' => 'Programar salidas y administrar esquemas',
        'salida.editar' => 'Editar salidas',
        'salida.cancelar' => 'Anular salidas',
        'salida.eliminar' => 'Eliminar salidas',
    ];

    public function getDescription(): string
    {
        return 'Salidas: esquema_salida, esquema_salida_momento, acciones salida.* y permiso Gestion Salidas';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS esquema_salida (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, intervalo_dias SMALLINT DEFAULT 1 NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, empresa_id INT DEFAULT NULL, trayecto_id INT NOT NULL, actualizado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_99694DB4521E1991 ON esquema_salida (empresa_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_99694DB48E3E79AA ON esquema_salida (trayecto_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_99694DB4F6167A1C ON esquema_salida (actualizado_por_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uq_esquema_salida_empresa_nombre ON esquema_salida (empresa_id, nombre)');
        $this->addSql('ALTER TABLE esquema_salida DROP CONSTRAINT IF EXISTS FK_99694DB4521E1991');
        $this->addSql('ALTER TABLE esquema_salida ADD CONSTRAINT FK_99694DB4521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE esquema_salida DROP CONSTRAINT IF EXISTS FK_99694DB48E3E79AA');
        $this->addSql('ALTER TABLE esquema_salida ADD CONSTRAINT FK_99694DB48E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE esquema_salida DROP CONSTRAINT IF EXISTS FK_99694DB4F6167A1C');
        $this->addSql('ALTER TABLE esquema_salida ADD CONSTRAINT FK_99694DB4F6167A1C FOREIGN KEY (actualizado_por_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE IF NOT EXISTS esquema_salida_momento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hora VARCHAR(5) NOT NULL, esquema_id INT NOT NULL, bus_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_C727EB62E0C19781 ON esquema_salida_momento (esquema_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_C727EB622546731D ON esquema_salida_momento (bus_id)');
        $this->addSql('ALTER TABLE esquema_salida_momento DROP CONSTRAINT IF EXISTS FK_C727EB62E0C19781');
        $this->addSql('ALTER TABLE esquema_salida_momento ADD CONSTRAINT FK_C727EB62E0C19781 FOREIGN KEY (esquema_id) REFERENCES esquema_salida (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE esquema_salida_momento DROP CONSTRAINT IF EXISTS FK_C727EB622546731D');
        $this->addSql('ALTER TABLE esquema_salida_momento ADD CONSTRAINT FK_C727EB622546731D FOREIGN KEY (bus_id) REFERENCES bus (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql(
            'INSERT INTO permiso (nombre) SELECT :nombre WHERE NOT EXISTS (SELECT 1 FROM permiso WHERE nombre = :nombre)',
            ['nombre' => 'Gestion Salidas'],
        );
        foreach (self::ACCIONES as $codigo => $nombre) {
            $this->addSql(
                'INSERT INTO action (codigo, nombre) SELECT :codigo, :nombre WHERE NOT EXISTS (SELECT 1 FROM action WHERE codigo = :codigo)',
                ['codigo' => $codigo, 'nombre' => $nombre],
            );
            $this->addSql(
                'INSERT INTO permiso_action (permiso_id, action_id)
                 SELECT p.id, a.id FROM permiso p, action a WHERE p.nombre = :nombre AND a.codigo = :codigo
                 ON CONFLICT DO NOTHING',
                ['nombre' => 'Gestion Salidas', 'codigo' => $codigo],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM permiso WHERE nombre = 'Gestion Salidas'");
        $this->addSql("DELETE FROM action WHERE codigo = 'salida.eliminar'");
        $this->addSql('DROP TABLE IF EXISTS esquema_salida_momento');
        $this->addSql('DROP TABLE IF EXISTS esquema_salida');
    }
}
