<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905085128 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE itinerario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legacy_id VARCHAR(50) DEFAULT NULL, status_id INT DEFAULT NULL, empresa_id INT DEFAULT NULL, bus_id INT DEFAULT NULL, piloto_id INT DEFAULT NULL, trayecto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11ECF4046BF700BD ON itinerario (status_id)');
        $this->addSql('CREATE INDEX IDX_11ECF404521E1991 ON itinerario (empresa_id)');
        $this->addSql('CREATE INDEX IDX_11ECF4042546731D ON itinerario (bus_id)');
        $this->addSql('CREATE INDEX IDX_11ECF4049AAD4A8D ON itinerario (piloto_id)');
        $this->addSql('CREATE INDEX IDX_11ECF4048E3E79AA ON itinerario (trayecto_id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF4046BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF404521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF4042546731D FOREIGN KEY (bus_id) REFERENCES bus (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF4049AAD4A8D FOREIGN KEY (piloto_id) REFERENCES piloto (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF4048E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT fk_95f4c7486bf700bd');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT fk_95f4c748521e1991');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT fk_95f4c7482546731d');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT fk_95f4c7489aad4a8d');
        $this->addSql('DROP TABLE salida');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT fk_8594a00426a36e51');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT FK_8594A00426A36E51 FOREIGN KEY (salida_id) REFERENCES itinerario (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE salida (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legacy_id VARCHAR(50) DEFAULT NULL, status_id INT DEFAULT NULL, empresa_id INT DEFAULT NULL, bus_id INT DEFAULT NULL, piloto_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_95f4c7486bf700bd ON salida (status_id)');
        $this->addSql('CREATE INDEX idx_95f4c748521e1991 ON salida (empresa_id)');
        $this->addSql('CREATE INDEX idx_95f4c7482546731d ON salida (bus_id)');
        $this->addSql('CREATE INDEX idx_95f4c7489aad4a8d ON salida (piloto_id)');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT fk_95f4c7486bf700bd FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT fk_95f4c748521e1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT fk_95f4c7482546731d FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT fk_95f4c7489aad4a8d FOREIGN KEY (piloto_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerario DROP CONSTRAINT FK_11ECF4046BF700BD');
        $this->addSql('ALTER TABLE itinerario DROP CONSTRAINT FK_11ECF404521E1991');
        $this->addSql('ALTER TABLE itinerario DROP CONSTRAINT FK_11ECF4042546731D');
        $this->addSql('ALTER TABLE itinerario DROP CONSTRAINT FK_11ECF4049AAD4A8D');
        $this->addSql('ALTER TABLE itinerario DROP CONSTRAINT FK_11ECF4048E3E79AA');
        $this->addSql('DROP TABLE itinerario');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT FK_8594A00426A36E51');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT fk_8594a00426a36e51 FOREIGN KEY (salida_id) REFERENCES salida (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
