<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614115530 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bus_marca (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_915CA4E23A909126 ON bus_marca (nombre)');
        $this->addSql('ALTER TABLE bus ADD codigo VARCHAR(15) NOT NULL');
        $this->addSql('ALTER TABLE bus ADD anoFabricacion INT NOT NULL');
        $this->addSql('ALTER TABLE bus ADD numeroSeguro VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD fechaVencimientoTarjetaOperaciones DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD numeroTarjetaOperaciones VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD descripcion TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD piloto_aux_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD marca_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus RENAME COLUMN legacy_id TO numeroTarjetaRodaje');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B69CE51A91C FOREIGN KEY (piloto_aux_id) REFERENCES piloto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B6981EF0041 FOREIGN KEY (marca_id) REFERENCES bus_marca (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F566B697BA2E6DA ON bus (numeroSeguro)');
        $this->addSql('CREATE INDEX IDX_2F566B69CE51A91C ON bus (piloto_aux_id)');
        $this->addSql('CREATE INDEX IDX_2F566B6981EF0041 ON bus (marca_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE bus_marca');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B69CE51A91C');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B6981EF0041');
        $this->addSql('DROP INDEX UNIQ_2F566B697BA2E6DA');
        $this->addSql('DROP INDEX IDX_2F566B69CE51A91C');
        $this->addSql('DROP INDEX IDX_2F566B6981EF0041');
        $this->addSql('ALTER TABLE bus ADD legacy_id VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE bus DROP codigo');
        $this->addSql('ALTER TABLE bus DROP anoFabricacion');
        $this->addSql('ALTER TABLE bus DROP numeroSeguro');
        $this->addSql('ALTER TABLE bus DROP fechaVencimientoTarjetaOperaciones');
        $this->addSql('ALTER TABLE bus DROP numeroTarjetaRodaje');
        $this->addSql('ALTER TABLE bus DROP numeroTarjetaOperaciones');
        $this->addSql('ALTER TABLE bus DROP descripcion');
        $this->addSql('ALTER TABLE bus DROP piloto_aux_id');
        $this->addSql('ALTER TABLE bus DROP marca_id');
    }
}
