<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723095214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vue_route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, vue_route_name VARCHAR(255) DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, params TEXT DEFAULT NULL, icon_id INT DEFAULT NULL, vue_route_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61B03F0154B9D732 ON vue_route (icon_id)');
        $this->addSql('CREATE INDEX IDX_61B03F01F43C36D6 ON vue_route (vue_route_id)');
        $this->addSql('CREATE TABLE vue_route_role (vue_route_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (vue_route_id, role_id))');
        $this->addSql('CREATE INDEX IDX_26DC9FC0F43C36D6 ON vue_route_role (vue_route_id)');
        $this->addSql('CREATE INDEX IDX_26DC9FC0D60322AC ON vue_route_role (role_id)');
        $this->addSql('CREATE TABLE vue_route_usuario_permitidos (vue_route_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (vue_route_id, usuario_id))');
        $this->addSql('CREATE INDEX IDX_13CAB7C6F43C36D6 ON vue_route_usuario_permitidos (vue_route_id)');
        $this->addSql('CREATE INDEX IDX_13CAB7C6DB38439E ON vue_route_usuario_permitidos (usuario_id)');
        $this->addSql('CREATE TABLE vue_route_usuario_denegados (vue_route_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (vue_route_id, usuario_id))');
        $this->addSql('CREATE INDEX IDX_339E88FCF43C36D6 ON vue_route_usuario_denegados (vue_route_id)');
        $this->addSql('CREATE INDEX IDX_339E88FCDB38439E ON vue_route_usuario_denegados (usuario_id)');
        $this->addSql('ALTER TABLE vue_route ADD CONSTRAINT FK_61B03F0154B9D732 FOREIGN KEY (icon_id) REFERENCES icon (id)');
        $this->addSql('ALTER TABLE vue_route ADD CONSTRAINT FK_61B03F01F43C36D6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id)');
        $this->addSql('ALTER TABLE vue_route_role ADD CONSTRAINT FK_26DC9FC0F43C36D6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vue_route_role ADD CONSTRAINT FK_26DC9FC0D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vue_route_usuario_permitidos ADD CONSTRAINT FK_13CAB7C6F43C36D6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vue_route_usuario_permitidos ADD CONSTRAINT FK_13CAB7C6DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vue_route_usuario_denegados ADD CONSTRAINT FK_339E88FCF43C36D6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vue_route_usuario_denegados ADD CONSTRAINT FK_339E88FCDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vue_route DROP CONSTRAINT FK_61B03F0154B9D732');
        $this->addSql('ALTER TABLE vue_route DROP CONSTRAINT FK_61B03F01F43C36D6');
        $this->addSql('ALTER TABLE vue_route_role DROP CONSTRAINT FK_26DC9FC0F43C36D6');
        $this->addSql('ALTER TABLE vue_route_role DROP CONSTRAINT FK_26DC9FC0D60322AC');
        $this->addSql('ALTER TABLE vue_route_usuario_permitidos DROP CONSTRAINT FK_13CAB7C6F43C36D6');
        $this->addSql('ALTER TABLE vue_route_usuario_permitidos DROP CONSTRAINT FK_13CAB7C6DB38439E');
        $this->addSql('ALTER TABLE vue_route_usuario_denegados DROP CONSTRAINT FK_339E88FCF43C36D6');
        $this->addSql('ALTER TABLE vue_route_usuario_denegados DROP CONSTRAINT FK_339E88FCDB38439E');
        $this->addSql('DROP TABLE vue_route');
        $this->addSql('DROP TABLE vue_route_role');
        $this->addSql('DROP TABLE vue_route_usuario_permitidos');
        $this->addSql('DROP TABLE vue_route_usuario_denegados');
    }
}
