<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Página web pública (ADR-023): departamento de los enclaves, configuración
 * de la página (recargo, venta activa, cierre), recargo y viajes de cada
 * pago web, mensajes de contacto y la acción `pagina.administrar` con su
 * permiso "Administracion Pagina Web". Idempotente.
 */
final class Version20261001120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Página web: enclave.departamento, configuracion_pagina, pago_web.recargo_porciento/viajes, mensaje_contacto, pagina.administrar';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE enclave ADD COLUMN IF NOT EXISTS departamento VARCHAR(60) DEFAULT NULL');

        $this->addSql('CREATE TABLE IF NOT EXISTS configuracion_pagina (id INT NOT NULL, recargo_porciento NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL, venta_en_linea BOOLEAN DEFAULT true NOT NULL, cierre_minutos INT DEFAULT 60 NOT NULL, actualizada_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actualizada_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_4F642CB8E39C682E ON configuracion_pagina (actualizada_por_id)');
        $this->addSql('ALTER TABLE configuracion_pagina DROP CONSTRAINT IF EXISTS FK_4F642CB8E39C682E');
        $this->addSql('ALTER TABLE configuracion_pagina ADD CONSTRAINT FK_4F642CB8E39C682E FOREIGN KEY (actualizada_por_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('INSERT INTO configuracion_pagina (id) VALUES (1) ON CONFLICT DO NOTHING');

        $this->addSql('ALTER TABLE pago_web ADD COLUMN IF NOT EXISTS recargo_porciento NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL');
        $this->addSql('ALTER TABLE pago_web ADD COLUMN IF NOT EXISTS viajes SMALLINT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE pago_web ADD COLUMN IF NOT EXISTS boleto_venta_regreso_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_93C628619B12E3D3 ON pago_web (boleto_venta_regreso_id)');
        $this->addSql('ALTER TABLE pago_web DROP CONSTRAINT IF EXISTS FK_93C628619B12E3D3');
        $this->addSql('ALTER TABLE pago_web ADD CONSTRAINT FK_93C628619B12E3D3 FOREIGN KEY (boleto_venta_regreso_id) REFERENCES boleto_venta (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE IF NOT EXISTS mensaje_contacto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, telefono VARCHAR(30) DEFAULT NULL, mensaje TEXT NOT NULL, idioma VARCHAR(5) NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, leido BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_mensaje_contacto_creado ON mensaje_contacto (creado_en)');

        $this->addSql(
            'INSERT INTO action (codigo, nombre) SELECT :codigo, :nombre WHERE NOT EXISTS (SELECT 1 FROM action WHERE codigo = :codigo)',
            ['codigo' => 'pagina.administrar', 'nombre' => 'Compras en línea y configuración de la página web'],
        );
        $this->addSql(
            'INSERT INTO permiso (nombre) SELECT :nombre WHERE NOT EXISTS (SELECT 1 FROM permiso WHERE nombre = :nombre)',
            ['nombre' => 'Administracion Pagina Web'],
        );
        $this->addSql(
            'INSERT INTO permiso_action (permiso_id, action_id)
             SELECT p.id, a.id FROM permiso p, action a WHERE p.nombre = :nombre AND a.codigo = :codigo
             ON CONFLICT DO NOTHING',
            ['nombre' => 'Administracion Pagina Web', 'codigo' => 'pagina.administrar'],
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM permiso WHERE nombre = 'Administracion Pagina Web'");
        $this->addSql("DELETE FROM action WHERE codigo = 'pagina.administrar'");
        $this->addSql('DROP TABLE IF EXISTS mensaje_contacto');
        $this->addSql('ALTER TABLE pago_web DROP COLUMN IF EXISTS boleto_venta_regreso_id');
        $this->addSql('ALTER TABLE pago_web DROP COLUMN IF EXISTS viajes');
        $this->addSql('ALTER TABLE pago_web DROP COLUMN IF EXISTS recargo_porciento');
        $this->addSql('DROP TABLE IF EXISTS configuracion_pagina');
        $this->addSql('ALTER TABLE enclave DROP COLUMN IF EXISTS departamento');
    }
}
