<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825165832 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, ruta VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, sort INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_NOMBRE ON menu (nombre)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_RUTA ON menu (ruta)');
        $this->addSql('CREATE TABLE menu_menu (parent_id INT NOT NULL, child_id INT NOT NULL, PRIMARY KEY (parent_id, child_id))');
        $this->addSql('CREATE INDEX IDX_B54ACADD727ACA70 ON menu_menu (parent_id)');
        $this->addSql('CREATE INDEX IDX_B54ACADDDD62C21B ON menu_menu (child_id)');
        $this->addSql('ALTER TABLE menu_menu ADD CONSTRAINT FK_B54ACADD727ACA70 FOREIGN KEY (parent_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_menu ADD CONSTRAINT FK_B54ACADDDD62C21B FOREIGN KEY (child_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu_menu DROP CONSTRAINT FK_B54ACADD727ACA70');
        $this->addSql('ALTER TABLE menu_menu DROP CONSTRAINT FK_B54ACADDDD62C21B');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_menu');
    }
}
