<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Croquis del bus (ADR-019):
 *
 * - `bus_senal`: chofer y puertas del croquis (en el legado, `bus_senal`).
 * - `asiento.planta`: 1 = baja, 2 = alta.
 * - Coordenadas de `asiento` consecutivas desde 1: las migradas del legado
 *   (0, 50, 100, …) pasan a `X / 50 + 1`. Solo se tocan los buses que aún
 *   están en el formato del legado (alguna coordenada 0 o ≥ 50).
 * - Planta de los asientos ya migrados: en los buses con asientos A y B, los
 *   A van a la planta alta (los B son los de la planta baja).
 * - Reinicia la identidad de `asiento.id`: la migración del legado insertaba
 *   ids explícitos y dejaba la secuencia atrás.
 */
final class Version20260926120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Croquis del bus: bus_senal (chofer/puertas), asiento.planta y coordenadas desde 1';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bus_senal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(20) NOT NULL, planta SMALLINT DEFAULT 1 NOT NULL, fila INT NOT NULL, columna INT NOT NULL, bus_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98555E7D2546731D ON bus_senal (bus_id)');
        $this->addSql('ALTER TABLE bus_senal ADD CONSTRAINT FK_98555E7D2546731D FOREIGN KEY (bus_id) REFERENCES bus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE asiento ADD planta SMALLINT DEFAULT 1 NOT NULL');

        $this->addSql(<<<'SQL'
            UPDATE asiento
               SET fila = COALESCE(fila, 0) / 50 + 1,
                   columna = COALESCE(columna, 0) / 50 + 1
             WHERE bus_id IN (
                   SELECT bus_id FROM asiento
                    GROUP BY bus_id
                   HAVING MIN(LEAST(COALESCE(fila, 0), COALESCE(columna, 0))) = 0
                       OR MAX(GREATEST(COALESCE(fila, 0), COALESCE(columna, 0))) >= 50
             )
            SQL);

        $this->addSql(<<<'SQL'
            UPDATE asiento a
               SET planta = 2
             WHERE a.clase = 'A'
               AND EXISTS (SELECT 1 FROM asiento b WHERE b.bus_id = a.bus_id AND b.clase = 'B')
            SQL);

        $this->addSql("SELECT setval(pg_get_serial_sequence('asiento', 'id'), COALESCE((SELECT MAX(id) FROM asiento), 0) + 1, false)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('UPDATE asiento SET fila = (fila - 1) * 50, columna = (columna - 1) * 50 WHERE fila IS NOT NULL AND columna IS NOT NULL');
        $this->addSql('ALTER TABLE bus_senal DROP CONSTRAINT FK_98555E7D2546731D');
        $this->addSql('DROP TABLE bus_senal');
        $this->addSql('ALTER TABLE asiento DROP planta');
    }
}
