<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008080522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Chat interno (ADR-026): chat_canal, chat_miembro, chat_mensaje';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat_canal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(10) NOT NULL, nombre VARCHAR(80) DEFAULT NULL, clave VARCHAR(30) DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actividad TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E0FC16C264E8588B ON chat_canal (clave)');
        $this->addSql('CREATE INDEX IDX_E0FC16C2FE35D8C4 ON chat_canal (creado_por_id)');
        $this->addSql('CREATE TABLE chat_mensaje (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, texto TEXT NOT NULL, adjuntos JSONB NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, canal_id INT NOT NULL, autor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D76DD16868DB5B2E ON chat_mensaje (canal_id)');
        $this->addSql('CREATE INDEX IDX_D76DD16814D45BBE ON chat_mensaje (autor_id)');
        $this->addSql('CREATE INDEX idx_chat_mensaje_canal ON chat_mensaje (canal_id, id)');
        $this->addSql('CREATE TABLE chat_miembro (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ultimo_leido INT NOT NULL, canal_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_731CFB068DB5B2E ON chat_miembro (canal_id)');
        $this->addSql('CREATE INDEX IDX_731CFB0DB38439E ON chat_miembro (usuario_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_chat_miembro ON chat_miembro (canal_id, usuario_id)');
        $this->addSql('ALTER TABLE chat_canal ADD CONSTRAINT FK_E0FC16C2FE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_mensaje ADD CONSTRAINT FK_D76DD16868DB5B2E FOREIGN KEY (canal_id) REFERENCES chat_canal (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_mensaje ADD CONSTRAINT FK_D76DD16814D45BBE FOREIGN KEY (autor_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_miembro ADD CONSTRAINT FK_731CFB068DB5B2E FOREIGN KEY (canal_id) REFERENCES chat_canal (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_miembro ADD CONSTRAINT FK_731CFB0DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_canal DROP CONSTRAINT FK_E0FC16C2FE35D8C4');
        $this->addSql('ALTER TABLE chat_mensaje DROP CONSTRAINT FK_D76DD16868DB5B2E');
        $this->addSql('ALTER TABLE chat_mensaje DROP CONSTRAINT FK_D76DD16814D45BBE');
        $this->addSql('ALTER TABLE chat_miembro DROP CONSTRAINT FK_731CFB068DB5B2E');
        $this->addSql('ALTER TABLE chat_miembro DROP CONSTRAINT FK_731CFB0DB38439E');
        $this->addSql('DROP TABLE chat_canal');
        $this->addSql('DROP TABLE chat_mensaje');
        $this->addSql('DROP TABLE chat_miembro');
    }
}
