<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260930180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Pago con Cybersource (ADR-021): comercio por empresa y estado del cobro entre pasos de 3-D Secure';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE credencial_pago (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comercio VARCHAR(100) NOT NULL, llave VARCHAR(100) NOT NULL, secreto_cifrado TEXT NOT NULL, empresa_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CED13DAF521E1991 ON credencial_pago (empresa_id)');
        $this->addSql('ALTER TABLE credencial_pago ADD CONSTRAINT FK_CED13DAF521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pago_web ADD estado_pasarela JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE pago_web ADD empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pago_web ADD CONSTRAINT FK_93C62861521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_93C62861521E1991 ON pago_web (empresa_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pago_web DROP CONSTRAINT FK_93C62861521E1991');
        $this->addSql('DROP INDEX IDX_93C62861521E1991');
        $this->addSql('ALTER TABLE pago_web DROP estado_pasarela');
        $this->addSql('ALTER TABLE pago_web DROP empresa_id');
        $this->addSql('DROP TABLE credencial_pago');
    }
}
