<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614073952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE piloto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(50) DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fechaNacimiento DATE DEFAULT NULL, numeroLicencia VARCHAR(40) DEFAULT NULL, fechaVencimientoLicencia DATE DEFAULT NULL, dpi VARCHAR(40) DEFAULT NULL, seguroSocial VARCHAR(50) DEFAULT NULL, codigo VARCHAR(10) NOT NULL, localidad_id INT DEFAULT NULL, status_id INT DEFAULT NULL, empresa_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8AE7BDC320332D99 ON piloto (codigo)');
        $this->addSql('CREATE INDEX IDX_8AE7BDC367707C89 ON piloto (localidad_id)');
        $this->addSql('CREATE INDEX IDX_8AE7BDC36BF700BD ON piloto (status_id)');
        $this->addSql('CREATE INDEX IDX_8AE7BDC3521E1991 ON piloto (empresa_id)');
        $this->addSql('ALTER TABLE piloto ADD CONSTRAINT FK_8AE7BDC367707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id)');
        $this->addSql('ALTER TABLE piloto ADD CONSTRAINT FK_8AE7BDC36BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE piloto ADD CONSTRAINT FK_8AE7BDC3521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE asiento DROP legacy_id');
        $this->addSql('ALTER TABLE bus ADD piloto_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B699AAD4A8D FOREIGN KEY (piloto_id) REFERENCES piloto (id)');
        $this->addSql('CREATE INDEX IDX_2F566B699AAD4A8D ON bus (piloto_id)');
        $this->addSql('DROP INDEX uniq_f41c9b25184998fc');
        $this->addSql('ALTER TABLE cliente DROP legacy_id');
        $this->addSql('ALTER TABLE empresa DROP legacy_id');
        $this->addSql('ALTER TABLE enclave DROP legacy_id');
        $this->addSql('DROP INDEX uniq_95f4c748184998fc');
        $this->addSql('ALTER TABLE salida ALTER legacy_id TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE tarifa DROP legacy_id');
        $this->addSql('DROP INDEX uniq_2265b05d184998fc');
        $this->addSql('ALTER TABLE usuario DROP legacy_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE piloto DROP CONSTRAINT FK_8AE7BDC367707C89');
        $this->addSql('ALTER TABLE piloto DROP CONSTRAINT FK_8AE7BDC36BF700BD');
        $this->addSql('ALTER TABLE piloto DROP CONSTRAINT FK_8AE7BDC3521E1991');
        $this->addSql('DROP TABLE piloto');
        $this->addSql('ALTER TABLE asiento ADD legacy_id VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B699AAD4A8D');
        $this->addSql('DROP INDEX IDX_2F566B699AAD4A8D');
        $this->addSql('ALTER TABLE bus DROP piloto_id');
        $this->addSql('ALTER TABLE cliente ADD legacy_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_f41c9b25184998fc ON cliente (legacy_id)');
        $this->addSql('ALTER TABLE empresa ADD legacy_id VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE enclave ADD legacy_id VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE salida ALTER legacy_id TYPE VARCHAR(255)');
        $this->addSql('CREATE UNIQUE INDEX uniq_95f4c748184998fc ON salida (legacy_id)');
        $this->addSql('ALTER TABLE tarifa ADD legacy_id VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario ADD legacy_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_2265b05d184998fc ON usuario (legacy_id)');
    }
}
