<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260810025309 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE layout_profile_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT DEFAULT 0 NOT NULL, layout_profile_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99EBE43A56FD02D8 ON layout_profile_role (layout_profile_id)');
        $this->addSql('CREATE INDEX IDX_99EBE43AD60322AC ON layout_profile_role (role_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_profile_role ON layout_profile_role (layout_profile_id, role_id)');
        $this->addSql('CREATE TABLE layout_profile_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT DEFAULT 0 NOT NULL, layout_profile_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6113A0656FD02D8 ON layout_profile_usuario (layout_profile_id)');
        $this->addSql('CREATE INDEX IDX_B6113A06DB38439E ON layout_profile_usuario (usuario_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_profile_usuario ON layout_profile_usuario (layout_profile_id, usuario_id)');
        $this->addSql('CREATE TABLE layout_schema_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT DEFAULT 0 NOT NULL, layout_schema_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9DA828452B839B4 ON layout_schema_item (layout_schema_id)');
        $this->addSql('CREATE INDEX IDX_A9DA8284F43C36D6 ON layout_schema_item (vue_route_id)');
        $this->addSql('ALTER TABLE layout_profile_role ADD CONSTRAINT FK_99EBE43A56FD02D8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_profile_role ADD CONSTRAINT FK_99EBE43AD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_profile_usuario ADD CONSTRAINT FK_B6113A0656FD02D8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_profile_usuario ADD CONSTRAINT FK_B6113A06DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_schema_item ADD CONSTRAINT FK_A9DA828452B839B4 FOREIGN KEY (layout_schema_id) REFERENCES layout_schema (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_schema_item ADD CONSTRAINT FK_A9DA8284F43C36D6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE layout_schema_sidebar_left DROP CONSTRAINT fk_ac9a047852b839b4');
        $this->addSql('ALTER TABLE layout_schema_sidebar_left DROP CONSTRAINT fk_ac9a0478f43c36d6');
        $this->addSql('ALTER TABLE layout_schema_sidebar_right DROP CONSTRAINT fk_a9ab9893f43c36d6');
        $this->addSql('ALTER TABLE layout_schema_sidebar_right DROP CONSTRAINT fk_a9ab989352b839b4');
        $this->addSql('ALTER TABLE layout_schema_topbar_right DROP CONSTRAINT fk_8a901ed052b839b4');
        $this->addSql('ALTER TABLE layout_schema_topbar_right DROP CONSTRAINT fk_8a901ed0f43c36d6');
        $this->addSql('ALTER TABLE profile_role DROP CONSTRAINT fk_e1a105fed60322ac');
        $this->addSql('ALTER TABLE profile_role DROP CONSTRAINT fk_e1a105fe56fd02d8');
        $this->addSql('ALTER TABLE profile_sidebar_left DROP CONSTRAINT fk_624d307956fd02d8');
        $this->addSql('ALTER TABLE profile_sidebar_left DROP CONSTRAINT fk_624d3079f43c36d6');
        $this->addSql('ALTER TABLE profile_sidebar_right DROP CONSTRAINT fk_de627f31f43c36d6');
        $this->addSql('ALTER TABLE profile_sidebar_right DROP CONSTRAINT fk_de627f3156fd02d8');
        $this->addSql('ALTER TABLE profile_topbar_right DROP CONSTRAINT fk_44472ad1f43c36d6');
        $this->addSql('ALTER TABLE profile_topbar_right DROP CONSTRAINT fk_44472ad156fd02d8');
        $this->addSql('ALTER TABLE profile_usuario DROP CONSTRAINT fk_f1db6ec156fd02d8');
        $this->addSql('ALTER TABLE profile_usuario DROP CONSTRAINT fk_f1db6ec1db38439e');
        $this->addSql('DROP TABLE layout_schema_sidebar_left');
        $this->addSql('DROP TABLE layout_schema_sidebar_right');
        $this->addSql('DROP TABLE layout_schema_topbar_right');
        $this->addSql('DROP TABLE profile_role');
        $this->addSql('DROP TABLE profile_sidebar_left');
        $this->addSql('DROP TABLE profile_sidebar_right');
        $this->addSql('DROP TABLE profile_topbar_right');
        $this->addSql('DROP TABLE profile_usuario');
        $this->addSql('ALTER TABLE collection_field_config RENAME COLUMN is_sortable TO sortable');
        $this->addSql('DROP INDEX uniq_f32bf59d3a909126');
        $this->addSql('ALTER TABLE layout_profile ADD enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE layout_profile ADD nota TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_profile ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_profile ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_profile DROP descripcion');
        $this->addSql('ALTER TABLE layout_profile ALTER nombre DROP NOT NULL');
        $this->addSql('ALTER TABLE layout_profile ALTER layout_schema_id SET NOT NULL');
        $this->addSql('DROP INDEX uniq_c3b656943a909126');
        $this->addSql('ALTER TABLE layout_schema ADD area VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE layout_schema ADD nota TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_schema ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_schema ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_schema ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_schema DROP descripcion');
        $this->addSql('ALTER TABLE layout_schema ALTER nombre DROP NOT NULL');
        $this->addSql('ALTER TABLE layout_schema ADD CONSTRAINT FK_C3B656946BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_C3B656946BF700BD ON layout_schema (status_id)');
        $this->addSql('ALTER TABLE vue_route DROP "position"');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE layout_schema_sidebar_left (layout_schema_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (layout_schema_id, vue_route_id))');
        $this->addSql('CREATE INDEX idx_ac9a047852b839b4 ON layout_schema_sidebar_left (layout_schema_id)');
        $this->addSql('CREATE INDEX idx_ac9a0478f43c36d6 ON layout_schema_sidebar_left (vue_route_id)');
        $this->addSql('CREATE TABLE layout_schema_sidebar_right (layout_schema_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (layout_schema_id, vue_route_id))');
        $this->addSql('CREATE INDEX idx_a9ab9893f43c36d6 ON layout_schema_sidebar_right (vue_route_id)');
        $this->addSql('CREATE INDEX idx_a9ab989352b839b4 ON layout_schema_sidebar_right (layout_schema_id)');
        $this->addSql('CREATE TABLE layout_schema_topbar_right (layout_schema_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (layout_schema_id, vue_route_id))');
        $this->addSql('CREATE INDEX idx_8a901ed0f43c36d6 ON layout_schema_topbar_right (vue_route_id)');
        $this->addSql('CREATE INDEX idx_8a901ed052b839b4 ON layout_schema_topbar_right (layout_schema_id)');
        $this->addSql('CREATE TABLE profile_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" INT NOT NULL, layout_profile_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e1a105fe56fd02d8 ON profile_role (layout_profile_id)');
        $this->addSql('CREATE INDEX idx_e1a105fed60322ac ON profile_role (role_id)');
        $this->addSql('CREATE TABLE profile_sidebar_left (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" INT NOT NULL, layout_profile_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_624d3079f43c36d6 ON profile_sidebar_left (vue_route_id)');
        $this->addSql('CREATE INDEX idx_624d307956fd02d8 ON profile_sidebar_left (layout_profile_id)');
        $this->addSql('CREATE TABLE profile_sidebar_right (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" INT NOT NULL, layout_profile_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_de627f31f43c36d6 ON profile_sidebar_right (vue_route_id)');
        $this->addSql('CREATE INDEX idx_de627f3156fd02d8 ON profile_sidebar_right (layout_profile_id)');
        $this->addSql('CREATE TABLE profile_topbar_right (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" INT NOT NULL, layout_profile_id INT NOT NULL, vue_route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_44472ad1f43c36d6 ON profile_topbar_right (vue_route_id)');
        $this->addSql('CREATE INDEX idx_44472ad156fd02d8 ON profile_topbar_right (layout_profile_id)');
        $this->addSql('CREATE TABLE profile_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" INT NOT NULL, layout_profile_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f1db6ec1db38439e ON profile_usuario (usuario_id)');
        $this->addSql('CREATE INDEX idx_f1db6ec156fd02d8 ON profile_usuario (layout_profile_id)');
        $this->addSql('ALTER TABLE layout_schema_sidebar_left ADD CONSTRAINT fk_ac9a047852b839b4 FOREIGN KEY (layout_schema_id) REFERENCES layout_schema (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_schema_sidebar_left ADD CONSTRAINT fk_ac9a0478f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_schema_sidebar_right ADD CONSTRAINT fk_a9ab9893f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_schema_sidebar_right ADD CONSTRAINT fk_a9ab989352b839b4 FOREIGN KEY (layout_schema_id) REFERENCES layout_schema (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_schema_topbar_right ADD CONSTRAINT fk_8a901ed052b839b4 FOREIGN KEY (layout_schema_id) REFERENCES layout_schema (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_schema_topbar_right ADD CONSTRAINT fk_8a901ed0f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_role ADD CONSTRAINT fk_e1a105fed60322ac FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_role ADD CONSTRAINT fk_e1a105fe56fd02d8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_sidebar_left ADD CONSTRAINT fk_624d307956fd02d8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_sidebar_left ADD CONSTRAINT fk_624d3079f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_sidebar_right ADD CONSTRAINT fk_de627f31f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_sidebar_right ADD CONSTRAINT fk_de627f3156fd02d8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_topbar_right ADD CONSTRAINT fk_44472ad1f43c36d6 FOREIGN KEY (vue_route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_topbar_right ADD CONSTRAINT fk_44472ad156fd02d8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_usuario ADD CONSTRAINT fk_f1db6ec156fd02d8 FOREIGN KEY (layout_profile_id) REFERENCES layout_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_usuario ADD CONSTRAINT fk_f1db6ec1db38439e FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE layout_profile_role DROP CONSTRAINT FK_99EBE43A56FD02D8');
        $this->addSql('ALTER TABLE layout_profile_role DROP CONSTRAINT FK_99EBE43AD60322AC');
        $this->addSql('ALTER TABLE layout_profile_usuario DROP CONSTRAINT FK_B6113A0656FD02D8');
        $this->addSql('ALTER TABLE layout_profile_usuario DROP CONSTRAINT FK_B6113A06DB38439E');
        $this->addSql('ALTER TABLE layout_schema_item DROP CONSTRAINT FK_A9DA828452B839B4');
        $this->addSql('ALTER TABLE layout_schema_item DROP CONSTRAINT FK_A9DA8284F43C36D6');
        $this->addSql('DROP TABLE layout_profile_role');
        $this->addSql('DROP TABLE layout_profile_usuario');
        $this->addSql('DROP TABLE layout_schema_item');
        $this->addSql('ALTER TABLE collection_field_config RENAME COLUMN sortable TO is_sortable');
        $this->addSql('ALTER TABLE layout_profile ADD descripcion VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_profile DROP enabled');
        $this->addSql('ALTER TABLE layout_profile DROP nota');
        $this->addSql('ALTER TABLE layout_profile DROP created_at');
        $this->addSql('ALTER TABLE layout_profile DROP updated_at');
        $this->addSql('ALTER TABLE layout_profile ALTER nombre SET NOT NULL');
        $this->addSql('ALTER TABLE layout_profile ALTER layout_schema_id DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_f32bf59d3a909126 ON layout_profile (nombre)');
        $this->addSql('ALTER TABLE layout_schema DROP CONSTRAINT FK_C3B656946BF700BD');
        $this->addSql('DROP INDEX IDX_C3B656946BF700BD');
        $this->addSql('ALTER TABLE layout_schema ADD descripcion VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE layout_schema DROP area');
        $this->addSql('ALTER TABLE layout_schema DROP nota');
        $this->addSql('ALTER TABLE layout_schema DROP created_at');
        $this->addSql('ALTER TABLE layout_schema DROP updated_at');
        $this->addSql('ALTER TABLE layout_schema DROP status_id');
        $this->addSql('ALTER TABLE layout_schema ALTER nombre SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_c3b656943a909126 ON layout_schema (nombre)');
        $this->addSql('ALTER TABLE vue_route ADD "position" INT DEFAULT NULL');
    }
}
