<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Taxonomía agnóstica y menús de navegación (ADR-018). Elimina las tablas del
 * intento anterior de menús (`menu`, `menu_role`, `menu_menu`, `menu_permiso`,
 * `menu_layout_assignment`, `submenu_order`), huérfanas y sin datos.
 */
final class Version20260925032716 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Taxonomy/TaxonomyNode + Menu/MenuItem/MenuPlacement; elimina las tablas huérfanas de menús';
    }

    public function up(Schema $schema): void
    {
        foreach (['submenu_order', 'menu_layout_assignment', 'menu_menu', 'menu_permiso', 'menu_role', 'menu'] as $table) {
            $this->addSql(sprintf('DROP TABLE IF EXISTS %s CASCADE', $table));
        }

        $this->addSql('CREATE TABLE taxonomy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, codigo VARCHAR(100) DEFAULT NULL, subject_class VARCHAR(100) DEFAULT NULL, max_depth INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD12B83D20332D99 ON taxonomy (codigo)');
        $this->addSql('CREATE TABLE taxonomy_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, subject_class VARCHAR(100) NOT NULL, subject_id INT NOT NULL, taxonomy_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E79D6AF29557E6F6 ON taxonomy_node (taxonomy_id)');
        $this->addSql('CREATE INDEX IDX_E79D6AF2727ACA70 ON taxonomy_node (parent_id)');
        $this->addSql('CREATE INDEX idx_taxonomy_node_subject ON taxonomy_node (subject_class, subject_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_taxonomy_node_subject ON taxonomy_node (taxonomy_id, subject_class, subject_id)');
        $this->addSql('ALTER TABLE taxonomy_node ADD CONSTRAINT FK_E79D6AF29557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_node ADD CONSTRAINT FK_E79D6AF2727ACA70 FOREIGN KEY (parent_id) REFERENCES taxonomy_node (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, taxonomy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D053A939557E6F6 ON menu (taxonomy_id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A939557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) NOT DEFERRABLE');
        $this->addSql('CREATE TABLE menu_role (menu_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (menu_id, role_id))');
        $this->addSql('CREATE INDEX IDX_9F267A24CCD7E912 ON menu_role (menu_id)');
        $this->addSql('CREATE INDEX IDX_9F267A24D60322AC ON menu_role (role_id)');
        $this->addSql('ALTER TABLE menu_role ADD CONSTRAINT FK_9F267A24CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_role ADD CONSTRAINT FK_9F267A24D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, icon_id INT NOT NULL, route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D55054B9D732 ON menu_item (icon_id)');
        $this->addSql('CREATE INDEX IDX_D754D55034ECB4E6 ON menu_item (route_id)');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55054B9D732 FOREIGN KEY (icon_id) REFERENCES icon (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55034ECB4E6 FOREIGN KEY (route_id) REFERENCES vue_route (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE menu_placement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, area VARCHAR(30) NOT NULL, position INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_519B123ACCD7E912 ON menu_placement (menu_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_menu_placement ON menu_placement (area, menu_id)');
        $this->addSql('ALTER TABLE menu_placement ADD CONSTRAINT FK_519B123ACCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Las tablas huérfanas eliminadas no se recrean: no tenían entidad ni datos.
        foreach (['menu_placement', 'menu_item', 'menu_role', 'menu', 'taxonomy_node', 'taxonomy'] as $table) {
            $this->addSql(sprintf('DROP TABLE %s', $table));
        }
    }
}
