<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527212510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero INT NOT NULL, clase VARCHAR(1) NOT NULL, fila INT DEFAULT NULL, columna INT DEFAULT NULL, bus_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71D6D35C2546731D ON asiento (bus_id)');
        $this->addSql('CREATE TABLE boleto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_compra TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_creador VARCHAR(255) DEFAULT NULL, salida_id INT NOT NULL, trayecto_id INT DEFAULT NULL, cliente_id INT NOT NULL, estacion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462E6E2526A36E51 ON boleto (salida_id)');
        $this->addSql('CREATE INDEX IDX_462E6E258E3E79AA ON boleto (trayecto_id)');
        $this->addSql('CREATE INDEX IDX_462E6E25DE734E51 ON boleto (cliente_id)');
        $this->addSql('CREATE INDEX IDX_462E6E252A4AF395 ON boleto (estacion_id)');
        $this->addSql('CREATE TABLE boleto_asiento (boleto_id INT NOT NULL, asiento_id INT NOT NULL, PRIMARY KEY (boleto_id, asiento_id))');
        $this->addSql('CREATE INDEX IDX_8594A0047F6F0A9B ON boleto_asiento (boleto_id)');
        $this->addSql('CREATE INDEX IDX_8594A004C642F3A8 ON boleto_asiento (asiento_id)');
        $this->addSql('CREATE TABLE bus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricula VARCHAR(50) NOT NULL, gama VARCHAR(50) DEFAULT NULL, empresa_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F566B69521E1991 ON bus (empresa_id)');
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, apellidos VARCHAR(255) NOT NULL, nif VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE empresa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, nif VARCHAR(20) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE enclave (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, direccion VARCHAR(255) DEFAULT NULL, latitud NUMERIC(10, 7) DEFAULT NULL, longitud NUMERIC(10, 7) DEFAULT NULL, tipo VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE salida (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hora_partida TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activa BOOLEAN NOT NULL, ruta_id INT NOT NULL, bus_id INT NOT NULL, empresa_id INT NOT NULL, tarifa_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_95F4C748ABBC4845 ON salida (ruta_id)');
        $this->addSql('CREATE INDEX IDX_95F4C7482546731D ON salida (bus_id)');
        $this->addSql('CREATE INDEX IDX_95F4C748521E1991 ON salida (empresa_id)');
        $this->addSql('CREATE INDEX IDX_95F4C748FE3B76B ON salida (tarifa_id)');
        $this->addSql('CREATE TABLE tarifa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, precio_clase_a NUMERIC(10, 2) NOT NULL, precio_clase_b NUMERIC(10, 2) DEFAULT NULL, empresa_id INT NOT NULL, bus_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A01B5DE3A909126 ON tarifa (nombre)');
        $this->addSql('CREATE INDEX IDX_A01B5DE521E1991 ON tarifa (empresa_id)');
        $this->addSql('CREATE INDEX IDX_A01B5DE2546731D ON tarifa (bus_id)');
        $this->addSql('CREATE TABLE tarifa_trayecto (tarifa_id INT NOT NULL, trayecto_id INT NOT NULL, PRIMARY KEY (tarifa_id, trayecto_id))');
        $this->addSql('CREATE INDEX IDX_BA6D42E9FE3B76B ON tarifa_trayecto (tarifa_id)');
        $this->addSql('CREATE INDEX IDX_BA6D42E98E3E79AA ON tarifa_trayecto (trayecto_id)');
        $this->addSql('CREATE TABLE trayecto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distancia_km NUMERIC(10, 2) DEFAULT NULL, duracion_estimada_minutos INT DEFAULT NULL, activo BOOLEAN NOT NULL, es_ruta BOOLEAN NOT NULL, origen_id INT NOT NULL, destino_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D1926D3393529ECD ON trayecto (origen_id)');
        $this->addSql('CREATE INDEX IDX_D1926D33E4360615 ON trayecto (destino_id)');
        $this->addSql('CREATE INDEX IDX_D1926D33727ACA70 ON trayecto (parent_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C2546731D FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E2526A36E51 FOREIGN KEY (salida_id) REFERENCES salida (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E258E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id)');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E25DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E252A4AF395 FOREIGN KEY (estacion_id) REFERENCES enclave (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT FK_8594A0047F6F0A9B FOREIGN KEY (boleto_id) REFERENCES boleto (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT FK_8594A004C642F3A8 FOREIGN KEY (asiento_id) REFERENCES asiento (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B69521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C748ABBC4845 FOREIGN KEY (ruta_id) REFERENCES trayecto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C7482546731D FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C748521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C748FE3B76B FOREIGN KEY (tarifa_id) REFERENCES tarifa (id)');
        $this->addSql('ALTER TABLE tarifa ADD CONSTRAINT FK_A01B5DE521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarifa ADD CONSTRAINT FK_A01B5DE2546731D FOREIGN KEY (bus_id) REFERENCES bus (id)');
        $this->addSql('ALTER TABLE tarifa_trayecto ADD CONSTRAINT FK_BA6D42E9FE3B76B FOREIGN KEY (tarifa_id) REFERENCES tarifa (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tarifa_trayecto ADD CONSTRAINT FK_BA6D42E98E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trayecto ADD CONSTRAINT FK_D1926D3393529ECD FOREIGN KEY (origen_id) REFERENCES enclave (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trayecto ADD CONSTRAINT FK_D1926D33E4360615 FOREIGN KEY (destino_id) REFERENCES enclave (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trayecto ADD CONSTRAINT FK_D1926D33727ACA70 FOREIGN KEY (parent_id) REFERENCES trayecto (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asiento DROP CONSTRAINT FK_71D6D35C2546731D');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E2526A36E51');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E258E3E79AA');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E25DE734E51');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E252A4AF395');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT FK_8594A0047F6F0A9B');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT FK_8594A004C642F3A8');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B69521E1991');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C748ABBC4845');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C7482546731D');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C748521E1991');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C748FE3B76B');
        $this->addSql('ALTER TABLE tarifa DROP CONSTRAINT FK_A01B5DE521E1991');
        $this->addSql('ALTER TABLE tarifa DROP CONSTRAINT FK_A01B5DE2546731D');
        $this->addSql('ALTER TABLE tarifa_trayecto DROP CONSTRAINT FK_BA6D42E9FE3B76B');
        $this->addSql('ALTER TABLE tarifa_trayecto DROP CONSTRAINT FK_BA6D42E98E3E79AA');
        $this->addSql('ALTER TABLE trayecto DROP CONSTRAINT FK_D1926D3393529ECD');
        $this->addSql('ALTER TABLE trayecto DROP CONSTRAINT FK_D1926D33E4360615');
        $this->addSql('ALTER TABLE trayecto DROP CONSTRAINT FK_D1926D33727ACA70');
        $this->addSql('DROP TABLE asiento');
        $this->addSql('DROP TABLE boleto');
        $this->addSql('DROP TABLE boleto_asiento');
        $this->addSql('DROP TABLE bus');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE empresa');
        $this->addSql('DROP TABLE enclave');
        $this->addSql('DROP TABLE salida');
        $this->addSql('DROP TABLE tarifa');
        $this->addSql('DROP TABLE tarifa_trayecto');
        $this->addSql('DROP TABLE trayecto');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
