<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008084603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Chat (ADR-026): archivos (chat_archivo), respuesta citada (chat_mensaje.respuesta_a_id) y canal de avisos del sistema';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat_archivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(160) NOT NULL, tipo VARCHAR(100) NOT NULL, tamano INT NOT NULL, ancho INT DEFAULT NULL, alto INT DEFAULT NULL, ruta VARCHAR(120) NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mensaje_id INT DEFAULT NULL, autor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_792778EB14D45BBE ON chat_archivo (autor_id)');
        $this->addSql('CREATE INDEX idx_chat_archivo_mensaje ON chat_archivo (mensaje_id)');
        $this->addSql('ALTER TABLE chat_archivo ADD CONSTRAINT FK_792778EB4C54F362 FOREIGN KEY (mensaje_id) REFERENCES chat_mensaje (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_archivo ADD CONSTRAINT FK_792778EB14D45BBE FOREIGN KEY (autor_id) REFERENCES usuario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_mensaje ADD respuesta_a_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE chat_mensaje ADD CONSTRAINT FK_D76DD1683B8D8648 FOREIGN KEY (respuesta_a_id) REFERENCES chat_mensaje (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D76DD1683B8D8648 ON chat_mensaje (respuesta_a_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_archivo DROP CONSTRAINT FK_792778EB4C54F362');
        $this->addSql('ALTER TABLE chat_archivo DROP CONSTRAINT FK_792778EB14D45BBE');
        $this->addSql('DROP TABLE chat_archivo');
        $this->addSql('ALTER TABLE chat_mensaje DROP CONSTRAINT FK_D76DD1683B8D8648');
        $this->addSql('DROP INDEX IDX_D76DD1683B8D8648');
        $this->addSql('ALTER TABLE chat_mensaje DROP respuesta_a_id');
    }
}
