<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260530103450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, legacy_id INT DEFAULT NULL, apellido VARCHAR(50) DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, status_id INT DEFAULT NULL, localidad_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX IDX_8D93D6496BF700BD ON "user" (status_id)');
        $this->addSql('CREATE INDEX IDX_8D93D64967707C89 ON "user" (localidad_id)');
        $this->addSql('CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3A76ED395 ON user_role (user_id)');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3D60322AC ON user_role (role_id)');
        $this->addSql('CREATE TABLE user_permiso (user_id INT NOT NULL, permiso_id INT NOT NULL, PRIMARY KEY (user_id, permiso_id))');
        $this->addSql('CREATE INDEX IDX_A577B594A76ED395 ON user_permiso (user_id)');
        $this->addSql('CREATE INDEX IDX_A577B5946CEFAD37 ON user_permiso (permiso_id)');
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ruta VARCHAR(255) DEFAULT NULL, nombre VARCHAR(255) DEFAULT NULL, status_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_47CC8C926BF700BD ON action (status_id)');
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expira TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, token VARCHAR(68) NOT NULL, scopes JSON NOT NULL, activo BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7BA2F5EBDB38439E ON api_token (usuario_id)');
        $this->addSql('CREATE TABLE collection_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field VARCHAR(255) NOT NULL, position INT NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, attrs JSON DEFAULT NULL, sortable BOOLEAN DEFAULT NULL, filterable BOOLEAN DEFAULT NULL, entity_config_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64EDBA5452A5B3AF ON collection_field_config (entity_config_id)');
        $this->addSql('CREATE TABLE entity_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_class VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_844909DB41BF2C66 ON entity_configuration (entity_class)');
        $this->addSql('CREATE TABLE form_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field VARCHAR(255) NOT NULL, position INT NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, attrs JSON DEFAULT NULL, group_name VARCHAR(255) DEFAULT NULL, entity_config_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9489E81C52A5B3AF ON form_field_config (entity_config_id)');
        $this->addSql('CREATE TABLE localidad (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, legacy_id INT DEFAULT NULL, nacion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F68E010A2D79AD9 ON localidad (nacion_id)');
        $this->addSql('CREATE TABLE pais (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, legacy_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE permiso (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) DEFAULT NULL, nota TEXT DEFAULT NULL, status_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD7AAB9E6BF700BD ON permiso (status_id)');
        $this->addSql('CREATE TABLE permiso_permiso (permiso_id INT NOT NULL, PRIMARY KEY (permiso_id))');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE role_role (role_id INT NOT NULL, PRIMARY KEY (role_id))');
        $this->addSql('CREATE TABLE role_permiso (role_id INT NOT NULL, permiso_id INT NOT NULL, PRIMARY KEY (role_id, permiso_id))');
        $this->addSql('CREATE INDEX IDX_41B70E65D60322AC ON role_permiso (role_id)');
        $this->addSql('CREATE INDEX IDX_41B70E656CEFAD37 ON role_permiso (permiso_id)');
        $this->addSql('CREATE TABLE role_action (role_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY (role_id, action_id))');
        $this->addSql('CREATE INDEX IDX_ECEA6D23D60322AC ON role_action (role_id)');
        $this->addSql('CREATE INDEX IDX_ECEA6D239D32F035 ON role_action (action_id)');
        $this->addSql('CREATE TABLE status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6496BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64967707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id)');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permiso ADD CONSTRAINT FK_A577B594A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permiso ADD CONSTRAINT FK_A577B5946CEFAD37 FOREIGN KEY (permiso_id) REFERENCES permiso (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C926BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EBDB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection_field_config ADD CONSTRAINT FK_64EDBA5452A5B3AF FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id)');
        $this->addSql('ALTER TABLE form_field_config ADD CONSTRAINT FK_9489E81C52A5B3AF FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id)');
        $this->addSql('ALTER TABLE localidad ADD CONSTRAINT FK_4F68E010A2D79AD9 FOREIGN KEY (nacion_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE permiso ADD CONSTRAINT FK_FD7AAB9E6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE permiso_permiso ADD CONSTRAINT FK_EC89D1FF6CEFAD37 FOREIGN KEY (permiso_id) REFERENCES permiso (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_role ADD CONSTRAINT FK_E9D6F8FED60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permiso ADD CONSTRAINT FK_41B70E65D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permiso ADD CONSTRAINT FK_41B70E656CEFAD37 FOREIGN KEY (permiso_id) REFERENCES permiso (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_action ADD CONSTRAINT FK_ECEA6D23D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_action ADD CONSTRAINT FK_ECEA6D239D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6496BF700BD');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64967707C89');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3A76ED395');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3D60322AC');
        $this->addSql('ALTER TABLE user_permiso DROP CONSTRAINT FK_A577B594A76ED395');
        $this->addSql('ALTER TABLE user_permiso DROP CONSTRAINT FK_A577B5946CEFAD37');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C926BF700BD');
        $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_7BA2F5EBDB38439E');
        $this->addSql('ALTER TABLE collection_field_config DROP CONSTRAINT FK_64EDBA5452A5B3AF');
        $this->addSql('ALTER TABLE form_field_config DROP CONSTRAINT FK_9489E81C52A5B3AF');
        $this->addSql('ALTER TABLE localidad DROP CONSTRAINT FK_4F68E010A2D79AD9');
        $this->addSql('ALTER TABLE permiso DROP CONSTRAINT FK_FD7AAB9E6BF700BD');
        $this->addSql('ALTER TABLE permiso_permiso DROP CONSTRAINT FK_EC89D1FF6CEFAD37');
        $this->addSql('ALTER TABLE role_role DROP CONSTRAINT FK_E9D6F8FED60322AC');
        $this->addSql('ALTER TABLE role_permiso DROP CONSTRAINT FK_41B70E65D60322AC');
        $this->addSql('ALTER TABLE role_permiso DROP CONSTRAINT FK_41B70E656CEFAD37');
        $this->addSql('ALTER TABLE role_action DROP CONSTRAINT FK_ECEA6D23D60322AC');
        $this->addSql('ALTER TABLE role_action DROP CONSTRAINT FK_ECEA6D239D32F035');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE user_permiso');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE collection_field_config');
        $this->addSql('DROP TABLE entity_configuration');
        $this->addSql('DROP TABLE form_field_config');
        $this->addSql('DROP TABLE localidad');
        $this->addSql('DROP TABLE pais');
        $this->addSql('DROP TABLE permiso');
        $this->addSql('DROP TABLE permiso_permiso');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_role');
        $this->addSql('DROP TABLE role_permiso');
        $this->addSql('DROP TABLE role_action');
        $this->addSql('DROP TABLE status');
    }
}
