<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260919092939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recorrido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legacy_id VARCHAR(50) DEFAULT NULL, estado VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, empresa_id INT DEFAULT NULL, bus_id INT DEFAULT NULL, piloto_id INT DEFAULT NULL, trayecto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A1543A8521E1991 ON recorrido (empresa_id)');
        $this->addSql('CREATE INDEX IDX_3A1543A82546731D ON recorrido (bus_id)');
        $this->addSql('CREATE INDEX IDX_3A1543A89AAD4A8D ON recorrido (piloto_id)');
        $this->addSql('CREATE INDEX IDX_3A1543A88E3E79AA ON recorrido (trayecto_id)');
        $this->addSql('CREATE INDEX idx_recorrido_fecha_empresa_trayecto ON recorrido (fecha, empresa_id, trayecto_id)');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A8521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A82546731D FOREIGN KEY (bus_id) REFERENCES bus (id)');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A89AAD4A8D FOREIGN KEY (piloto_id) REFERENCES piloto (id)');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A88E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT fk_8594a00471caa3e7');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT fk_8594a0046bf700bd');
        $this->addSql('DROP INDEX idx_8594a0046bf700bd');
        $this->addSql('DROP INDEX idx_8594a00471caa3e7');
        $this->addSql('ALTER TABLE servicio DROP CONSTRAINT fk_cb86f22a2546731d');
        $this->addSql('ALTER TABLE servicio DROP CONSTRAINT fk_cb86f22a9aad4a8d');
        $this->addSql('ALTER TABLE servicio DROP CONSTRAINT fk_cb86f22a8e3e79aa');
        $this->addSql('ALTER TABLE servicio DROP CONSTRAINT fk_cb86f22a6bf700bd');
        $this->addSql('ALTER TABLE servicio DROP CONSTRAINT fk_cb86f22a521e1991');
        $this->addSql('DROP TABLE servicio');
        $this->addSql('ALTER TABLE boleto_asiento ADD estado VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE boleto_asiento ADD recorrido_id INT NOT NULL');
        $this->addSql('ALTER TABLE boleto_asiento DROP status_id');
        $this->addSql('ALTER TABLE boleto_asiento DROP servicio_id');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT FK_8594A0047A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8594A0047A331FF ON boleto_asiento (recorrido_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_boleto_asiento_asiento_trayecto_recorrido ON boleto_asiento (asiento_id, trayecto_id, recorrido_id)');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT fk_2f566b69ce51a91c');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT fk_2f566b699aad4a8d');
        $this->addSql('DROP INDEX idx_2f566b69ce51a91c');
        $this->addSql('DROP INDEX idx_2f566b699aad4a8d');
        $this->addSql('ALTER TABLE bus DROP piloto_id');
        $this->addSql('ALTER TABLE bus DROP piloto_aux_id');
        $this->addSql('ALTER TABLE usuario ADD empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('CREATE INDEX IDX_2265B05D521E1991 ON usuario (empresa_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE servicio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legacy_id VARCHAR(50) DEFAULT NULL, status_id INT DEFAULT NULL, empresa_id INT DEFAULT NULL, bus_id INT DEFAULT NULL, piloto_id INT DEFAULT NULL, trayecto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cb86f22a521e1991 ON servicio (empresa_id)');
        $this->addSql('CREATE INDEX idx_cb86f22a6bf700bd ON servicio (status_id)');
        $this->addSql('CREATE INDEX idx_cb86f22a2546731d ON servicio (bus_id)');
        $this->addSql('CREATE INDEX idx_cb86f22a9aad4a8d ON servicio (piloto_id)');
        $this->addSql('CREATE INDEX idx_cb86f22a8e3e79aa ON servicio (trayecto_id)');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT fk_cb86f22a2546731d FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT fk_cb86f22a9aad4a8d FOREIGN KEY (piloto_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT fk_cb86f22a8e3e79aa FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT fk_cb86f22a6bf700bd FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT fk_cb86f22a521e1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto_asiento DROP CONSTRAINT FK_8594A0047A331FF');
        $this->addSql('DROP INDEX IDX_8594A0047A331FF');
        $this->addSql('DROP INDEX uq_boleto_asiento_asiento_trayecto_recorrido');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A8521E1991');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A82546731D');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A89AAD4A8D');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A88E3E79AA');
        $this->addSql('DROP TABLE recorrido');
        $this->addSql('ALTER TABLE boleto_asiento ADD servicio_id INT NOT NULL');
        $this->addSql('ALTER TABLE boleto_asiento ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_asiento DROP estado');
        $this->addSql('ALTER TABLE boleto_asiento DROP recorrido_id');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT fk_8594a00471caa3e7 FOREIGN KEY (servicio_id) REFERENCES servicio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto_asiento ADD CONSTRAINT fk_8594a0046bf700bd FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_8594a0046bf700bd ON boleto_asiento (status_id)');
        $this->addSql('CREATE INDEX idx_8594a00471caa3e7 ON boleto_asiento (servicio_id)');
        $this->addSql('ALTER TABLE bus ADD piloto_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD piloto_aux_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT fk_2f566b69ce51a91c FOREIGN KEY (piloto_aux_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT fk_2f566b699aad4a8d FOREIGN KEY (piloto_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2f566b69ce51a91c ON bus (piloto_aux_id)');
        $this->addSql('CREATE INDEX idx_2f566b699aad4a8d ON bus (piloto_id)');
        $this->addSql('ALTER TABLE usuario DROP CONSTRAINT FK_2265B05D521E1991');
        $this->addSql('DROP INDEX IDX_2265B05D521E1991');
        $this->addSql('ALTER TABLE usuario DROP empresa_id');
    }
}
