<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260929223832 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Venta de asientos (ADR-021): canales, agencias, reservas web, pagos, catálogos de pago/moneda/documento';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE agencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, nit VARCHAR(20) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, telefono VARCHAR(30) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, saldo BIGINT DEFAULT 0 NOT NULL, moneda VARCHAR(3) DEFAULT \'GTQ\' NOT NULL, porcentaje_bonificacion NUMERIC(5, 2) DEFAULT NULL, activo BOOLEAN DEFAULT true NOT NULL, legacy_id VARCHAR(50) DEFAULT NULL, empresa_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EB6C2B99521E1991 ON agencia (empresa_id)');
        $this->addSql('CREATE TABLE agencia_movimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(20) NOT NULL, monto BIGINT NOT NULL, saldo_resultante BIGINT NOT NULL, referencia VARCHAR(50) DEFAULT NULL, observacion VARCHAR(255) DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agencia_id INT NOT NULL, usuario_id INT DEFAULT NULL, boleto_venta_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DABE9C73A6F796BE ON agencia_movimiento (agencia_id)');
        $this->addSql('CREATE INDEX IDX_DABE9C73DB38439E ON agencia_movimiento (usuario_id)');
        $this->addSql('CREATE INDEX IDX_DABE9C7397E11BE8 ON agencia_movimiento (boleto_venta_id)');
        $this->addSql('CREATE INDEX idx_agencia_movimiento_agencia_fecha ON agencia_movimiento (agencia_id, fecha)');
        $this->addSql('CREATE TABLE moneda (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sigla VARCHAR(3) NOT NULL, nombre VARCHAR(40) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B00B2B2D801B7D4B ON moneda (sigla)');
        $this->addSql('CREATE TABLE pago_web (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token UUID NOT NULL, estado VARCHAR(20) NOT NULL, referencia_pasarela VARCHAR(100) DEFAULT NULL, autorizacion VARCHAR(50) DEFAULT NULL, comprador JSON NOT NULL, marca VARCHAR(12) DEFAULT NULL, ultimos4 VARCHAR(4) DEFAULT NULL, mensaje VARCHAR(500) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, monto_monto INT NOT NULL, monto_moneda VARCHAR(3) NOT NULL, boleto_venta_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_93C6286197E11BE8 ON pago_web (boleto_venta_id)');
        $this->addSql('CREATE INDEX idx_pago_web_token ON pago_web (token)');
        $this->addSql('CREATE UNIQUE INDEX uq_pago_web_referencia ON pago_web (referencia_pasarela)');
        $this->addSql('CREATE TABLE reserva_asiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token UUID NOT NULL, expira_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creada_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recorrido_id INT NOT NULL, asiento_id INT NOT NULL, trayecto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B005E48E7A331FF ON reserva_asiento (recorrido_id)');
        $this->addSql('CREATE INDEX IDX_B005E48EC642F3A8 ON reserva_asiento (asiento_id)');
        $this->addSql('CREATE INDEX IDX_B005E48E8E3E79AA ON reserva_asiento (trayecto_id)');
        $this->addSql('CREATE INDEX idx_reserva_asiento_recorrido_expira ON reserva_asiento (recorrido_id, expira_en)');
        $this->addSql('CREATE INDEX idx_reserva_asiento_token ON reserva_asiento (token)');
        $this->addSql('CREATE UNIQUE INDEX uq_reserva_asiento_token_asiento ON reserva_asiento (token, asiento_id)');
        $this->addSql('CREATE TABLE tipo_documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sigla VARCHAR(3) DEFAULT NULL, nombre VARCHAR(50) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54DF91893A909126 ON tipo_documento (nombre)');
        $this->addSql('CREATE TABLE tipo_pago (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(50) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEF0887B3A909126 ON tipo_pago (nombre)');
        $this->addSql('ALTER TABLE agencia ADD CONSTRAINT FK_EB6C2B99521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE agencia_movimiento ADD CONSTRAINT FK_DABE9C73A6F796BE FOREIGN KEY (agencia_id) REFERENCES agencia (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agencia_movimiento ADD CONSTRAINT FK_DABE9C73DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agencia_movimiento ADD CONSTRAINT FK_DABE9C7397E11BE8 FOREIGN KEY (boleto_venta_id) REFERENCES boleto_venta (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pago_web ADD CONSTRAINT FK_93C6286197E11BE8 FOREIGN KEY (boleto_venta_id) REFERENCES boleto_venta (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserva_asiento ADD CONSTRAINT FK_B005E48E7A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserva_asiento ADD CONSTRAINT FK_B005E48EC642F3A8 FOREIGN KEY (asiento_id) REFERENCES asiento (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserva_asiento ADD CONSTRAINT FK_B005E48E8E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boleto_asiento ADD observacion VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD canal VARCHAR(20) DEFAULT \'estacion\' NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD estado VARCHAR(20) DEFAULT \'confirmada\' NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD estado_facturacion VARCHAR(20) DEFAULT \'no_aplica\' NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD error_facturacion VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD cortesia BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD enviar_correo BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD referencia_pago VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD token_publico UUID DEFAULT NULL');
        // Ventas ya migradas: total = suma de sus boletos (el mapeo no lleva default).
        $this->addSql('ALTER TABLE boleto_venta ADD total_monto INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD total_moneda VARCHAR(3) DEFAULT \'GTQ\' NOT NULL');
        $this->addSql('UPDATE boleto_venta v SET total_monto = s.total FROM (SELECT boleto_venta_id, SUM(precio_monto) AS total FROM boleto_asiento GROUP BY boleto_venta_id) s WHERE s.boleto_venta_id = v.id');
        $this->addSql('ALTER TABLE boleto_venta ALTER total_monto DROP DEFAULT');
        $this->addSql('ALTER TABLE boleto_venta ALTER total_moneda DROP DEFAULT');
        $this->addSql('ALTER TABLE boleto_venta ADD estacion_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD agencia_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD cliente_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD tipo_pago_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD moneda_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto_venta ALTER usuario_id DROP NOT NULL');
        $this->addSql('ALTER TABLE boleto_venta ADD CONSTRAINT FK_4046761F2A4AF395 FOREIGN KEY (estacion_id) REFERENCES enclave (id)');
        $this->addSql('ALTER TABLE boleto_venta ADD CONSTRAINT FK_4046761FA6F796BE FOREIGN KEY (agencia_id) REFERENCES agencia (id)');
        $this->addSql('ALTER TABLE boleto_venta ADD CONSTRAINT FK_4046761FDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id)');
        $this->addSql('ALTER TABLE boleto_venta ADD CONSTRAINT FK_4046761F7002A220 FOREIGN KEY (tipo_pago_id) REFERENCES tipo_pago (id)');
        $this->addSql('ALTER TABLE boleto_venta ADD CONSTRAINT FK_4046761FB77634D2 FOREIGN KEY (moneda_id) REFERENCES moneda (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4046761F823D5230 ON boleto_venta (token_publico)');
        $this->addSql('CREATE INDEX IDX_4046761F2A4AF395 ON boleto_venta (estacion_id)');
        $this->addSql('CREATE INDEX IDX_4046761FA6F796BE ON boleto_venta (agencia_id)');
        $this->addSql('CREATE INDEX IDX_4046761FDE734E51 ON boleto_venta (cliente_id)');
        $this->addSql('CREATE INDEX IDX_4046761F7002A220 ON boleto_venta (tipo_pago_id)');
        $this->addSql('CREATE INDEX IDX_4046761FB77634D2 ON boleto_venta (moneda_id)');
        $this->addSql('CREATE INDEX idx_boleto_venta_estado_creada ON boleto_venta (estado, created_at)');
        $this->addSql('ALTER TABLE cliente ADD numero_documento VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente ADD tipo_documento_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente ADD nacionalidad_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B25F6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B25AB8DC0F8 FOREIGN KEY (nacionalidad_id) REFERENCES pais (id)');
        $this->addSql('CREATE INDEX IDX_F41C9B25F6939175 ON cliente (tipo_documento_id)');
        $this->addSql('CREATE INDEX IDX_F41C9B25AB8DC0F8 ON cliente (nacionalidad_id)');
        $this->addSql('CREATE INDEX idx_cliente_nit ON cliente (nit)');
        $this->addSql('ALTER TABLE factura ADD fecha_certificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE factura ADD certificador_nit VARCHAR(25) DEFAULT NULL');
        $this->addSql('ALTER TABLE factura ADD certificador_nombre VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE factura ADD xml TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE factura ADD total_monto INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE factura ADD total_moneda VARCHAR(3) DEFAULT \'GTQ\' NOT NULL');
        $this->addSql('UPDATE factura f SET total_monto = v.total_monto, total_moneda = v.total_moneda FROM boleto_venta v WHERE v.factura_id = f.id');
        $this->addSql('ALTER TABLE factura ALTER total_monto DROP DEFAULT');
        $this->addSql('ALTER TABLE factura ALTER total_moneda DROP DEFAULT');
        $this->addSql('ALTER TABLE factura ALTER dte TYPE BIGINT');
        $this->addSql('ALTER TABLE usuario ADD agencia_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario ADD estacion_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DA6F796BE FOREIGN KEY (agencia_id) REFERENCES agencia (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D2A4AF395 FOREIGN KEY (estacion_id) REFERENCES enclave (id)');
        $this->addSql('CREATE INDEX IDX_2265B05DA6F796BE ON usuario (agencia_id)');
        $this->addSql('CREATE INDEX IDX_2265B05D2A4AF395 ON usuario (estacion_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE agencia DROP CONSTRAINT FK_EB6C2B99521E1991');
        $this->addSql('ALTER TABLE agencia_movimiento DROP CONSTRAINT FK_DABE9C73A6F796BE');
        $this->addSql('ALTER TABLE agencia_movimiento DROP CONSTRAINT FK_DABE9C73DB38439E');
        $this->addSql('ALTER TABLE agencia_movimiento DROP CONSTRAINT FK_DABE9C7397E11BE8');
        $this->addSql('ALTER TABLE pago_web DROP CONSTRAINT FK_93C6286197E11BE8');
        $this->addSql('ALTER TABLE reserva_asiento DROP CONSTRAINT FK_B005E48E7A331FF');
        $this->addSql('ALTER TABLE reserva_asiento DROP CONSTRAINT FK_B005E48EC642F3A8');
        $this->addSql('ALTER TABLE reserva_asiento DROP CONSTRAINT FK_B005E48E8E3E79AA');
        $this->addSql('ALTER TABLE boleto_asiento DROP observacion');
        $this->addSql('ALTER TABLE boleto_venta DROP CONSTRAINT FK_4046761F2A4AF395');
        $this->addSql('ALTER TABLE boleto_venta DROP CONSTRAINT FK_4046761FA6F796BE');
        $this->addSql('ALTER TABLE boleto_venta DROP CONSTRAINT FK_4046761FDE734E51');
        $this->addSql('ALTER TABLE boleto_venta DROP CONSTRAINT FK_4046761F7002A220');
        $this->addSql('ALTER TABLE boleto_venta DROP CONSTRAINT FK_4046761FB77634D2');
        $this->addSql('DROP INDEX UNIQ_4046761F823D5230');
        $this->addSql('DROP INDEX IDX_4046761F2A4AF395');
        $this->addSql('DROP INDEX IDX_4046761FA6F796BE');
        $this->addSql('DROP INDEX IDX_4046761FDE734E51');
        $this->addSql('DROP INDEX IDX_4046761F7002A220');
        $this->addSql('DROP INDEX IDX_4046761FB77634D2');
        $this->addSql('DROP INDEX idx_boleto_venta_estado_creada');
        $this->addSql('ALTER TABLE boleto_venta DROP canal');
        $this->addSql('ALTER TABLE boleto_venta DROP estado');
        $this->addSql('ALTER TABLE boleto_venta DROP estado_facturacion');
        $this->addSql('ALTER TABLE boleto_venta DROP error_facturacion');
        $this->addSql('ALTER TABLE boleto_venta DROP cortesia');
        $this->addSql('ALTER TABLE boleto_venta DROP enviar_correo');
        $this->addSql('ALTER TABLE boleto_venta DROP referencia_pago');
        $this->addSql('ALTER TABLE boleto_venta DROP token_publico');
        $this->addSql('ALTER TABLE boleto_venta DROP total_monto');
        $this->addSql('ALTER TABLE boleto_venta DROP total_moneda');
        $this->addSql('ALTER TABLE boleto_venta DROP estacion_id');
        $this->addSql('ALTER TABLE boleto_venta DROP agencia_id');
        $this->addSql('ALTER TABLE boleto_venta DROP cliente_id');
        $this->addSql('ALTER TABLE boleto_venta DROP tipo_pago_id');
        $this->addSql('ALTER TABLE boleto_venta DROP moneda_id');
        $this->addSql('ALTER TABLE boleto_venta ALTER usuario_id SET NOT NULL');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B25F6939175');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B25AB8DC0F8');
        $this->addSql('DROP INDEX IDX_F41C9B25F6939175');
        $this->addSql('DROP INDEX IDX_F41C9B25AB8DC0F8');
        $this->addSql('DROP INDEX idx_cliente_nit');
        $this->addSql('ALTER TABLE cliente DROP numero_documento');
        $this->addSql('ALTER TABLE cliente DROP tipo_documento_id');
        $this->addSql('ALTER TABLE cliente DROP nacionalidad_id');
        $this->addSql('ALTER TABLE factura DROP fecha_certificacion');
        $this->addSql('ALTER TABLE factura DROP certificador_nit');
        $this->addSql('ALTER TABLE factura DROP certificador_nombre');
        $this->addSql('ALTER TABLE factura DROP xml');
        $this->addSql('ALTER TABLE factura DROP total_monto');
        $this->addSql('ALTER TABLE factura DROP total_moneda');
        $this->addSql('ALTER TABLE factura ALTER dte TYPE INT');
        $this->addSql('ALTER TABLE usuario DROP CONSTRAINT FK_2265B05DA6F796BE');
        $this->addSql('ALTER TABLE usuario DROP CONSTRAINT FK_2265B05D2A4AF395');
        $this->addSql('DROP INDEX IDX_2265B05DA6F796BE');
        $this->addSql('DROP INDEX IDX_2265B05D2A4AF395');
        $this->addSql('ALTER TABLE usuario DROP agencia_id');
        $this->addSql('ALTER TABLE usuario DROP estacion_id');
        $this->addSql('DROP TABLE agencia');
        $this->addSql('DROP TABLE agencia_movimiento');
        $this->addSql('DROP TABLE moneda');
        $this->addSql('DROP TABLE pago_web');
        $this->addSql('DROP TABLE reserva_asiento');
        $this->addSql('DROP TABLE tipo_documento');
        $this->addSql('DROP TABLE tipo_pago');
    }
}
