xdebug.client_host = host.docker.internal
; max_execution_time = 30
; max_input_time = 30

xdebug.start_with_request=yes 

xdebug.log_level= 3

; xdebug.file_link_format="vscode://file/%f:%l&/app/>/home/alcides/modelo/backend/"
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
