/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./components/icons/AppIcon.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DemoPlugingGraphql: typeof import('./components/DemoPlugingGraphql.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FkAutoComplete: typeof import('./components/formkit/FkAutoComplete.vue')['default']
    FkCascadeSelect: typeof import('./components/formkit/FkCascadeSelect.vue')['default']
    FkCheckbox: typeof import('./components/formkit/FkCheckbox.vue')['default']
    FkDatePicker: typeof import('./components/formkit/FkDatePicker.vue')['default']
    FkInputMask: typeof import('./components/formkit/FkInputMask.vue')['default']
    FkInputNumber: typeof import('./components/formkit/FkInputNumber.vue')['default']
    FkInputText: typeof import('./components/formkit/FkInputText.vue')['default']
    FkMultiSelect: typeof import('./components/formkit/FkMultiSelect.vue')['default']
    FkPassword: typeof import('./components/formkit/FkPassword.vue')['default']
    FkRadioButton: typeof import('./components/formkit/FkRadioButton.vue')['default']
    FkSelect: typeof import('./components/formkit/FkSelect.vue')['default']
    FkSelectButton: typeof import('./components/formkit/FkSelectButton.vue')['default']
    FkTextArea: typeof import('./components/formkit/FkTextArea.vue')['default']
    FkToggleSwitch: typeof import('./components/formkit/FkToggleSwitch.vue')['default']
    FkTreeSelect: typeof import('./components/formkit/FkTreeSelect.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    GraphQLOrmDemo: typeof import('./components/GraphQLOrmDemo.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PageHead: typeof import('./components/common/PageHead.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SidebarLeft: typeof import('./components/layout/SidebarLeft.vue')['default']
    SidebarRight: typeof import('./components/layout/SidebarRight.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeEditor: typeof import('./components/ThemeEditor.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
  }
}
